## A. POSITIONAL AND LABEL-BASED SLICING

In [60]:
import pandas as pd

cars = pd.read_csv('cars.csv')

columnname_list = cars.columns.tolist()

cars_6_to_10 = cars.iloc[5:10]

selected_columns = cars_6_to_10.loc[:, ['Model', 'mpg', 'cyl', 'hp', 'gear']]

print ("Shape of cars =", cars.shape)
print("List of column names: ", columnname_list)
print("\ncars 6 to 10: ")
display(cars_6_to_10)
print("Selected columns for cars 6 to 10: ")
display(selected_columns)

Shape of cars = (32, 12)
List of column names:  ['Model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']

cars 6 to 10:

        Model   mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
5     Valiant  18.1    6  225.0  105  2.76  3.46  20.22   1   0     3     1
6  Duster 360  14.3    8  360.0  245  3.21  3.57  15.84   0   0     3     4
7   Merc 240D  24.4    4  146.7   62  3.69  3.19  20.00   1   0     4     2
8    Merc 230  22.8    4  140.8   95  3.92  3.15  22.90   1   0     4     2
9    Merc 280  19.2    6  167.6  123  3.92  3.44  18.30   1   0     4     4

Selected columns for cars 6 to 10:

        Model   mpg  cyl   hp  gear
5     Valiant  18.1    6  105     3
6  Duster 360  14.3    8  245     3
7   Merc 240D  24.4    4   62     4
8    Merc 230  22.8    4   95     4
9    Merc 280  19.2    6  123     4

## B. MODEL LOOKUP

In [55]:
toyota = cars.loc[(cars['Model'] == 'Toyota Corolla')]
pontiac = cars.loc[(cars['Model'] == 'Pontiac Firebird'), ['Model', 'mpg', 'hp', 'wt']]

print("Toyota Corolla")
display(toyota)
print("Pontiac Firebird")
display(pontiac)

Toyota Corolla

             Model   mpg  cyl  disp  hp  drat     wt  qsec  vs  am  gear  carb
19  Toyota Corolla  33.9    4  71.1  65  4.22  1.835  19.9   1   1     4     1

Pontiac Firebird

               Model   mpg   hp     wt
24  Pontiac Firebird  19.2  175  3.845

## C. MULTI-MODEL SUBSETTING

In [56]:
selected_cars = cars.loc[(cars['Model'] == 'Datsun 710') | (cars['Model'] == 'Lotus Europa') | (cars['Model'] == 'Ferrari Dino'), ['Model', 'mpg', 'cyl', 'hp', 'gear']]

display(selected_cars)
print("Selected cars shape = ", selected_cars.shape)

           Model   mpg  cyl   hp  gear
2     Datsun 710  22.8    4   93     4
27  Lotus Europa  30.4    4  113     5
29  Ferrari Dino  19.7    6  175     5

Selected cars shape =  (3, 5)

## *End*